{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div id = "serialisation" data-max-size-x="{$cellMaxSizeX}" data-max-size-y="{$cellMaxSizeY}" data-margin-x="{$gridMarginX}" data-margin-y="{$gridMarginY}" data-max-cols="{$gridMaxCols}" data-grid-dimensionx="{$gridDimensionX}" data-grid-dimensiony="{$gridDimensionY}" style ="display:none;">{$gridData}</div>
<div class="gridster gridster-border" attribute_id="{$attributeId}" style = "width:{$gridWidth}px;">
    <ul></ul>
    <input type="text" class="grid-input" hidden="hidden" id="grid-input" name="grid" value='{$gridData}'>
    <div class="buttons">
        <a class="add">add</a>
    </div>
</div>