{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $gridData = getgrid($attribute.content.gridString)}
<div id ="accessname" style ="display:none;" val ='{ezini("AdminUrlForModules", "SiteURL")}'></div>
<div class="grid-width" attribute_id = "{$attribute.id}">Grid width <input type="text" value="{$attribute.content.gridWidth}" name="gridwidth"> <a class="gridster-reload">Reload</a></div>
    <div id="gridster-data">
        {include uri="design:content/datatype/edit/gridarea.tpl" cellMaxSizeX=$attribute.content.cellMaxSizeX cellMaxSizeY=$attribute.content.cellMaxSizeY gridMarginX=$attribute.content.gridMarginX gridMarginY=$attribute.content.gridMarginY gridDimensionX=$attribute.content.gridDimensionX gridDimensionY=$attribute.content.gridDimensionY gridMaxCols=$attribute.content.gridMaxCols attributeId=$attribute.id gridData=$gridData gridWidth=$attribute.content.gridWidth}
    </div>
{undef $gridData}