{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*<div style = "width:{$data.width}px; height: {$data.height}px; position: absolute; top: {$data.top}; left: {$data.left};" class="cell default size-x-{$data.size_x} size-y-{$data.size_y}" data-row="{$data.row}" data-col="{$data.col}" data-sizex="{$data.size_x}" data-sizey="{$data.size_y}">
    <div class="cell-content">
        <p>Default template</p>
        <p>NodeId: {$data.node_id}<p/>
        <p>Class id: {$class}<p/>
        <p>NodeName: {$cellNellNode.name}<p/>
        <p>Size: {$data.size_x}x{$data.size_y}<p/>
    </div>
</div>*}