{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<div class="block"></div>
{*{if $class_attribute.data_text}*}
{*{/if}*}
{*{section var=Multioptions loop=$class_attribute.content.multioption_list}*}
{*<div class="block">*}
{*<label>{$Multioptions.item.name}:</label>*}
{*<ul>*}
    {*{section var=Option loop=$Multioptions.item.options}*}
        {*<li>{$Option.item.value}</li>*}
    {*{/section}*}
{*<ul>*}
{*</div>*}
{*{/section}*}
